name: Super-Linter

on:
  push:

jobs:
  super-lint:
    name: Super Linter checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v4

      - name: Run Super-linter
        uses: github/super-linter@v3
        env:
          DEFAULT-BRANCH: main
          SECRET_TOKEN: ${{ secrets.Secret_token }}

      
     
  
  
